### ISSUE TITLE
In dark mode, pages briefly flash to white when navigating

### ISSUE THREAD

**Issue by davepagurek** [bocoup/p5.js-website#207]
![flash-white](https://github.com/bocoup/p5.js-website/assets/5315059/0ee7af69-558d-4d53-bfaf-599b071fb8f7)

I wonder if there's a way we can get a black background earlier in the loading process to avoid that?

**Comment by stalgiag** [comment]
Thanks for the screen recording. Very important one to note. There are a few options here that we can experiment with. It is tricky since we don't have a SPA. Perhaps we can get closer to that experience using [view transitions ](https://docs.astro.build/en/guides/view-transitions/) but yes a loading fallback might also work.
