### ISSUE TITLE
Reference localization

### ISSUE THREAD

**Issue by limzykenneth** [bocoup/p5.js-website#245]
I'm not sure if this is in the process of being address but currently the localized version of the reference is not looking quite right with many entries missing, from a glance, looks like all the translated ones? Notable excepting `rectMode()`.

Speaking of `rectMode()`, there's another issue that shows up in localization which is the one line description for Chinese.
![Screenshot 2024-04-24 21:01:55](https://github.com/bocoup/p5.js-website/assets/7543950/d32c1504-8231-4866-867c-f70e41659e06)

Because Chinese uses a different character for a full stop (`。`), simply truncating the first sentence before the first regular full stop character will cause the entire description to be rendered.

**Comment by stalgiag** [comment]
Oh interesting that is a new bug. It does look like most (but not all) reference entries are missing for non-english locales. I'll put a high priority on this one.

For the second issue - I think that using the actual one-line descriptions from the library source will address this long term but for now perhaps we could use the  `。` in addition to the period in our regex for breaking out the one-line description.

**Comment by stalgiag** [comment]
Ah I see. It is because References are being filtered by category but those categories have been translated. This is [similar to this discussion here](https://github.com/bocoup/p5.js-website/pull/227#discussion_r1577052499). I'll figure something out. Will likely require a node script to pull all of the translated categories out.
